### ISSUE TITLE
aimrocks error

### ISSUE THREAD

**Issue by suyihhhhh** [tcbenchstack/tcbench#1]
你好，我在win10上安装tcbench的过程中遇到了一些问题，在进行到python -m pip install tcbench的时候，提示报错aimrocks==0.4.0，尝试了一些方法但是不太理想，可以告诉我要怎么解决吗？
![屏幕截图 2023-12-15 161507](https://github.com/tcbenchstack/tcbench/assets/88757270/e9c68a40-d5b0-402f-b94e-783500583a5c)

**Comment by CMV-1** [comment]
I'm having the same issue.  Can you help me?@tcbenchstack

**Comment by tcbenchstack** [comment]
@suyihhhhh
Thanks for raising the problem. 

To be honest, I never considered using windows per-se (I tested only linux and macos).

Checking pipy, aim does not have a build for windows
(see https://pypi.org/project/aim/3.17.5/#files) so pip is trying to compile it from source and it stops because it requires aimrocks which also does not have a build for windows (https://pypi.org/project/aimrocks/0.4.0/#files).

To quickly bypass the problem, I recommend you to use WSL on windows

@CMV-1
Are you also trying to install directly on windows?

**Comment by suyihhhhh** [comment]
I will try the method you mentioned, thank you very much for your answer!

**Comment by suyihhhhh** [comment]
I'm sorry to bother you again. I attempted to successfully build tcbench using WSL, but encountered a multiprocessing error during the second artifacts run while testing the “_tcbench campaign augment-at-loading_”. The error specifically occurred in the "data augmentation (rotate)" step.The error message is as follows. Could you please advise me on how to resolve it? @tcbenchstack 
![image](https://github.com/tcbenchstack/tcbench/assets/88757270/1a7e5ce0-15c0-4a0c-b5e3-6589d034aba6)
![image](https://github.com/tcbenchstack/tcbench/assets/88757270/fe51d2b2-4d85-4d65-b00a-59842a7abe0c)

Here is the code that I entered：
![屏幕截图 2023-12-27 194852](https://github.com/tcbenchstack/tcbench/assets/88757270/755b0925-e9c4-47b8-940c-b7c60290e5cc)

**Comment by tcbenchstack** [comment]
@suyihhhhh 
glad to hear you managed to use WSL

I'll close this issue because the problem you mentioned in unrelated to the current issue
Please open a new issue
